#!/bin/bash
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=80
#SBATCH --time=10:00:00
#SBATCH --mail-type=end 
#SBATCH --mail-user=hunt.feng@usask.ca 

cd $SCRATCH/magnetic-nozzle-warpx
source warpx.profile --cpu 
dirname="diags$(date '+%Y%m%d%H%M')"
mkdir $dirname
mpirun python run_simulation.py -out $dirname -cpu &> $dirname/output.log
