#!/bin/bash
#SBATCH --nodes=1
#SBATCH --gpus-per-node=4
#SBATCH --time=1:00:00
#SBATCH --mem=1G
#SBATCH --mail-type=end 
#SBATCH --mail-user=hunt.feng@usask.ca 

cd $SCRATCH/magnetic-nozzle-warpx
source warpx_gpu.profile
dirname="diags$(date '+%Y%m%d%H%M')"
mkdir $dirname
srun --gpus=4 python run_simulation_gpu.py $dirname &> $dirname/output.log
