#!/bin/bash
#SBATCH --nodes=1
#SBATCH --gpus-per-node=1
#SBATCH --ntasks-per-node=1
#SBATCH --time=0:30:00
#SBATCH --mem=1G
#SBATCH --output=slurm_%j.out
#SBATCH --mail-type=end 
#SBATCH --mail-user=hunt.feng@usask.ca 

cd $SCRATCH/magnetic-nozzle-warpx
source warpx_gpu.profile
dirname="diags$(date '+%Y%m%d%H%M')"
mkdir $dirname
srun --gpus-per-task=1 python run_simulation_gpu.py $dirname &> $dirname/output.log